### ISSUE TITLE
Skip parsing errors 

### ISSUE THREAD

**Issue by cayasso** [WebReflection/i18n-utils#4]
Hi @WebReflection 
I am running into some issues when running `18n-utils` in my react app, the issue is with some imports like `.css` where I get `Unexpected token` or in some cases missing modules in `node_modules` that I don't have control of but are throwing. Can we skip these maybe by adding a `try/catch` in the `findRequire` method. You can always output the errors as warnings but continue with the parsing.

Another issue that I had was with `NODE_PATH` env var, where I have it defined to this `NODE_PATH=src` to avoid in my project paths like these `../../../components`, but when running `i18n-utils` it errors with `MODULE_NOT_FOUND` the only way to make it work is by setting `NODE_PATH` to the absolute path of `src`. Any ideas?

**Comment by WebReflection** [comment]
I use `require.resolve` and `process.cwd(path)` to resolve correctly modules, if you change your paths and `require` fails I'm not sure how to fix.

What's the issue in `NODE_PATH=$(pwd) i18n-utils ./project/main.js` ?

about the try catch, maybe you file PR after testing?

**Comment by WebReflection** [comment]
latest `0.3.2` has a try catch around the require that does not involve `.js` files.
