### ISSUE TITLE
Common i18n Features/Standards

### ISSUE THREAD

**Issue by dogoku** [WebReflection/i18n-utils#5]
Since you jumped into the i18n world, i figured I could help by providing a list of the common features and standards found in other i18n, for your consideration. I understand most of these are probably out of the scope of this library, just trying to help.

## Features:
1. [Plural support](https://www.i18next.com/plurals.html) (perhaps via [Intl](https://github.com/tc39/proposal-intl-plural-rules))
2. [Nesting](https://www.i18next.com/nesting.html) (is nesting TL even possible?)
3. [Date/Number formatting](https://www.i18next.com/formatting.html) (perhaps via Intl)
4. [Context Variants](https://www.i18next.com/context.html)
5. Plugins & Build/Dev tools

## Standards:
1. [ICU Standard support](http://site.icu-project.org/) 
2. [ECMA 402 Intl Support](https://tc39.github.io/ecma402/)

## References:
- https://rxaviers.github.io/javascript-globalization/ - Great comparision of i18n libs (bit outdated)
- https://developers.google.com/international/ - Lots of i18n resources by Google
- http://projectfluent.io/ - Mozilla's new i18n project. Very ambitious, sadly no legacy support
- https://www.i18next.com/ - Probably the most popular i18n lib right now
- https://github.com/tc39/ecma402

**Comment by WebReflection** [comment]
Thanks for taking time to write this.

I'd like to instantly state that I am aware there are other i18n libs and yet nothing is close to my proposed approach.

Developers should try to remove their old-style i18n biases and think differently.

As example, everything that can be done via Intl *should* be done via Intl so there's nothing to do here.

Plurals are also already possible:

```js
i18n`I had ${apples === 1 ?
  i18n`one apple` :
  i18n`${apples} apples`
}`;
```

that answers nested template literals too. You write like you would in your native language and where you want i18n you use `i18n` as tag function.

You run this utility, and you have the whole db for you in multiple language.

You load the db incrementally or all at once, you set the locale, and you are done.

You can use the `i18n-dummy` tag until you are sure everything works with the real `i18n-yummy`.
