### ISSUE TITLE
Doesn't let me update the already existing translations

### ISSUE THREAD

**Issue by jaschaio** [WebReflection/i18n-utils#7]
Whenever I run it again it doesn't seem to recognize the already existing translations within the database.

I tried with the option parameters too `npx i18n-utils -o i18n.db.json -l en -t es,de main.js` but I still always have to start from zero. It does recognize that there is an existing database as it gives me the existing `(es, de)` languages as options to the `you are translating '${locale}' to which language?` question. But on the actual website that open's within the Browser it doesn't displays the existing translations.

Btw. this is by far the most convenient i18n library I could find. Together with `hyperHTML` it's absolutely stunning how fast you can get great results.

**Comment by WebReflection** [comment]
can you try without `npx` ? maybe that's somehow cleaning up or changing env each time ? thanks

**Comment by jaschaio** [comment]
I still get the same problem :/ whats somehow weird is that even if I execute the command in my root directory it actually creates the database in the `./components` sub-directory. But even than it should recognize the existing database within that directory on subsequent runs.

**Comment by WebReflection** [comment]
after a second look, I'm afraid I've left some change locally without ever pushing it.

Version 0.4 will work as you expect, sorry for the hassle.
