### ISSUE TITLE
i18n calls inside hyper.wire() not recognized

### ISSUE THREAD

**Issue by jaschaio** [WebReflection/i18n-utils#8]
This might be my fault or missing understanding of [hyperHTML](https://github.com/WebReflection/hyperHTML). But it seems that I can't use i18n inside the the `hyper.wire()`` ` method.

This is recognized by `i18n-utils`:

```let test = i18n`Simple test i18n message`;```

This as well:

```let test = `This is a template literal ${ i18n`Simple test i18n message` } inside another one`;```

But this isn't:

```let test = hyper.wire()`This is a template literal ${ i18n`Simple test i18n message` } inside another one`;```

Is this intended?

Thanks

**Comment by WebReflection** [comment]
> Is this intended?

nope, quite the opposite, but I think the issue is that the AST parser is not walking through template literals interpolations.

Will have a look ASAP, thanks for filling this.

**Comment by WebReflection** [comment]
please let me know how it works now, thanks.
